# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 17:58
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('clubPrice', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=8), max_digits=8)),
                ('priceNote', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(default='请简介上线课程', max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('detail', models.CharField(blank=True, max_length=5000)),
                ('showcase', models.ImageField(upload_to=courses.models.upload_showcase_location, verbose_name='showcases')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expire', models.DateField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='categories.Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.Vendor')),
            ],
        ),
    ]
