# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('linkman', models.CharField(max_length=20)),
                ('cellphone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('logo', models.ImageField(upload_to=vendors.models.upload_logo_location)),
                ('isCertificated', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
